### ISSUE TITLE
where to find the `https://github.com/darwinanddavis/worldmaps/blob/gh-pages/data/BREVE2.ttf?raw=true` file?

### ISSUE THREAD

**Issue by liamxg** [darwinanddavis/worldmaps#1]
Dear @darwinanddavis ,

Could you please upload the `https://github.com/darwinanddavis/worldmaps/blob/gh-pages/data/BREVE2.ttf?raw=true` file, thanks.

Best,
Liam

**Comment by darwinanddavis** [comment]
Hi Liam, that's a custom font that I probably used to create the labels.
You can find it here

https://www.dafont.com/breve-sc.font

You can upload it into R using ggfont or a similar package. Let me know how
you go.

M

**Comment by liamxg** [comment]
@darwinanddavis ,

Thanks. 

Best,
Liam
