### ISSUE TITLE
where to find the `bushfire/data/Historical Bushfire Boundaries.gdb/a00000009.gdbtable` file?

### ISSUE THREAD

**Issue by liamxg** [darwinanddavis/worldmaps#2]
Dear @darwinanddavis ,

Could I know where to find the `bushfire/data/Historical Bushfire Boundaries.gdb/a00000009.gdbtable` file?

Thanks.

Best,
Xingguang

**Comment by darwinanddavis** [comment]
Hi Xingguang, you can download it all here. There is a bit of pre-processing required as the data as quite large so I suggest tackling isolated sections of Aus and/or using smoothing functions on the polygons for each geometry boundary to reduce the object sizes.  

https://ecat.ga.gov.au/geonetwork/srv/api/records/a82c263f-dba6-457a-aafd-bf869fe7171a

^^

**Comment by liamxg** [comment]
Dear @darwinanddavis ,

Thanks again.

Best,
Liam
