### ISSUE TITLE
the link `http://data.insideairbnb.com/united-states/ca/san-francisco/2019-12-04/data/listings.csv.gz` can not open

### ISSUE THREAD

**Issue by liamxg** [darwinanddavis/worldmaps#3]
Dear @darwinanddavis ,

I find that the link `http://data.insideairbnb.com/united-states/ca/san-francisco/2019-12-04/data/listings.csv.gz` can not open, how should I do ?

Best,
Liam

**Comment by darwinanddavis** [comment]
Hi. it's not good practice to store large data files such as csv on github, so you can access all listing data here for various cities here.

https://insideairbnb.com/get-the-data/

^^

**Comment by liamxg** [comment]
Dear @darwinanddavis ,

Thanks.

Best,
Liam
